# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ukt1g5kLRCg_frbkilOCdNO2UGsERqlq

***Phase 1***
"""

import pandas as pd
import numpy as np
from pandas.tseries.offsets import DateOffset
df=pd.read_csv("/content/Nassau Candy Distributor (1).csv")

df.head()

"""****Phaase 2****

**Cleaning Data Step 1 to Find Factory To Customer Routes**
"""

#Cleaning Data Step 1
factory_map = {
    'Wonka Bar - Nutty Crunch Surprise': "Lot's O' Nuts",
    'Wonka Bar - Fudge Mallows': "Lot's O' Nuts",
    'Wonka Bar -Scrumdiddlyumptious': "Lot's O' Nuts",
    'Wonka Bar - Milk Chocolate': "Wicked Choccy's",
    'Wonka Bar - Triple Dazzle Caramel': "Wicked Choccy's",
    'Laffy Taffy': 'Sugar Shack',
    'SweeTARTS': 'Sugar Shack',
    'Nerds': 'Sugar Shack',
    'Fun Dip': 'Sugar Shack',
    'Fizzy Lifting Drinks': 'Sugar Shack',
    'Everlasting Gobstopper': 'Secret Factory',
    'Lickable Wallpaper': 'Secret Factory',
    'Wonka Gum': 'Secret Factory',
    'Kazookles': 'Secret Factory',
    'Hair Toffee': 'The Other Factory'
}
df['Factory'] = df['Product Name'].map(factory_map)
print(df['Factory'].value_counts())

print(df['Product Name'].unique())

"""**Cleaning Dataset Step 2 to Find LEAD TIME(which routes are fatser)**"""

#CONVERT ORDER DATE TO DATETIME
df['Order Date']=pd.to_datetime(df['Order Date'],errors='coerce')

#CONVERT SHIP DATE TO DATETIME
df['Ship Date'] = pd.to_datetime(df['Ship Date'],errors='coerce')

# 2. FINAL FIX - Force Ship Year = Order Year
df['Ship Date'] = df.apply(
    lambda r: r['Ship Date'].replace(year=r['Order Date'].year) if pd.notna(r['Ship Date']) and pd.notna(r['Order Date']) else r['Ship Date'],
    axis=1
)

# Recalculate temp lead time
df['Lead_Time_Days'] = (df['Ship Date'] - df['Order Date']).dt.days
mask_negative = df['Lead_Time_Days'] < 0

# Fix negatives by adding 1 year safely (handles Feb 29)
df.loc[mask_negative, 'Ship Date'] = df.loc[mask_negative, 'Ship Date'] + DateOffset(years=1)

#LEAD TIME(time between order placed and order shipped.)
#Lower = faster factory.
df['Lead_Time_Days'] = (df['Ship Date'] - df['Order Date']).dt.days

df_clean = df[(df['Lead_Time_Days'] >= 0) & (df['Lead_Time_Days'] <= 365)].copy()
#So increase threshold to 365 days (1 year) — standard for production data:
#.copy makes the file independent and sepearate.

print(f"Original rows: {len(df)}")
print(f"Clean rows: {len(df_clean)}")

"""***Phase 3(Route Efficieny, time and cost)***

**We Now Use The Clean Data**
"""

# Clean column spaces first
df_clean.columns = df_clean.columns.str.strip()

# Group by Factory instead of Route
factory_summary = df_clean.groupby('Factory').agg(
    Avg_Lead_Time=('Lead_Time_Days', 'mean'),
    Avg_Cost=('Cost', 'mean'),
    Total_Orders=('Order ID', 'count'),
    Total_Profit=('Gross Profit', 'sum')
).round(2).sort_values('Avg_Lead_Time', ascending=False)

print(factory_summary)

#Grouping by Factory(calucate the avg using .agg( give agg the variables u need to find the average or calculation))
#Avg_Lead_Time = which factory is slowest to ship
#Avg_Cost = which factory is expensive
#Sort = worst performer on top — that's your insight for Power BI

"""The primary operational bottleneck is Wicked Choccy's and Lot's O' Nuts. While Sugar Shack shows the highest average lead time (223 days), its low order volume (n=9) makes it statistically insignificant. Lot's O' Nuts handles 58% of clean orders (2365/4130) with a 174-day lead time, representing the greatest systemic delay. Secret Factory has the highest Avg Cost ($16.33) but low profit contribution."""

print(df['Lead_Time_Days'].describe())
print(df[['Order Date','Ship Date','Lead_Time_Days']].head(10))

print(df_clean.columns.tolist())

# Export clean data for Power BI
df_clean.to_csv('Nassau_Candy_Clean_4130.csv', index=False)
print("Exported for Power BI")

from google.colab import files
files.download('Nassau_Candy_Clean_4130.csv')
#turns the file into clean version of itself.
